name: portfolio_eriel
description: "Portfolio"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.4.0
  firebase_storage: ^12.3.3
  cloud_firestore: ^5.4.0
  url_launcher: ^6.3.0
  file_picker: ^8.1.2
  reorderables: ^0.6.0
  numberpicker: ^2.1.2
  intl: ^0.19.0
  pdf: ^3.11.1
  pdfrx: ^1.0.93
  file_saver: ^0.2.14
  universal_platform: ^1.1.0
  http: ^1.1.0
  markdown_widget: ^2.3.2+8
  printing: ^5.14.2
  htmltopdfwidgets: ^1.1.0


  # State
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4

  # Network
  dio: ^5.4.3+1
  retrofit: ^4.1.0

  # Navigation
  go_router: ^14.3.0

  # UI
  cupertino_icons: ^1.0.8
  dynamic_height_grid_view: ^0.0.4
  cached_network_image: ^3.4.0
  cached_network_image_web: ^1.3.1
  carousel_slider: ^5.0.0
  json_annotation: ^4.9.0
  glass_kit: ^4.0.1

  # TODO este override es necesario para evitar el error: Undefined name 'platformViewRegistry'
  # Utilizamos el fork de alguien q lo reparo en este paquete, pero debemos regresar al paquete
  # original cuando se arregle ese error.
  # html_editor_enhanced: ^2.6.0
  html_editor_enhanced:
    git: https://github.com/eoinzy/html-editor-enhanced

  flutter_widget_from_html: ^0.16.0
  super_banners: ^0.0.1

  share_plus: ^10.1.4



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/developers.json
    - assets/background.png
    - assets/avatars/
    - assets/projects/
    - assets/images/
    - assets/resume/
